# default values
all:
  sfSymfonyTemplatingViewPlugin:
    rules:
      php:
#        - { loader: sfTemplateLoaderDoctrine, renderer: php, model: Template }
        - { loader: sfTemplateLoaderFilesystemForSymfony1, renderer: php }
      smarty:
#        - { loader: sfTemplateLoaderDoctrine, renderer: php, model: Template }
        - { loader: sfTemplateLoaderFilesystemForSymfony1, renderer: smarty }
    renderers:
      smarty: sfTemplateRendererSmarty
